# Generated by Django 3.2 on 2022-04-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220408_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=models.FileField(default='', upload_to='video/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
