# Generated by Django 3.2 on 2022-04-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_videopost_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_status',
            new_name='is_active_admin',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='comment_status',
            new_name='is_comment_status',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='comment_status_admin',
            new_name='is_comment_status_admin',
        ),
        migrations.RenameField(
            model_name='photopost',
            old_name='comment_status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='photopost',
            old_name='comment_status_admin',
            new_name='is_active_admin',
        ),
        migrations.RenameField(
            model_name='photopost',
            old_name='photo_status',
            new_name='is_comment_status',
        ),
        migrations.RenameField(
            model_name='videopost',
            old_name='comment_status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='videopost',
            old_name='comment_status_admin',
            new_name='is_active_admin',
        ),
        migrations.RenameField(
            model_name='videopost',
            old_name='video_status',
            new_name='is_comment_status',
        ),
        migrations.AddField(
            model_name='photopost',
            name='is_comment_status_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videopost',
            name='is_comment_status_admin',
            field=models.BooleanField(default=True),
        ),
    ]
