# Generated by Django 3.2 on 2022-04-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='subcomments',
            name='date_posted',
        ),
    ]
