# Generated by Django 3.2 on 2022-04-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220418_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcomments',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcomments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcomments',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
